import { ROUTER_ADDRESS, ROUTER_ETH_ADDRESS, PANCAKE_ROUTER_ADDRESS, UNISWAP_ROUTER_ADDRESS } from './index'

export const SPHYNX_ROUTER = {
  56: ROUTER_ADDRESS,
  1: ROUTER_ETH_ADDRESS,
}

export const V2_ROUTER = {
  56: PANCAKE_ROUTER_ADDRESS,
  1: UNISWAP_ROUTER_ADDRESS,
}
